thunder_print.print_article_type.*:
  type: config_entity
  label: 'Print article type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    grid:
      type: integer
      label: 'Grid'
    idms:
      type: string
      label: 'IDMS xml content'
    status:
      type: boolean
      label: 'Status'
    thumbnail_uuid:
      type: string
      label: 'Thumbnail uuid'
    description:
      type: string
      label: 'Description'

action.configuration.print_article_publish_action:
  type: action_configuration_default
  label: 'Publish print article'

action.configuration.print_article_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish print article'
