thunder_print.tag_mapping.*:
  type: config_entity
  label: 'Tag Mapping config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    mapping_type:
      type: string
      label: 'Mapping type'
    mapping:
      type: sequence
      label: 'Mapping of tags'
      sequence:
        type: string
        # For >= 8.4
        orderby: key
    options:
      type: thunder_print.tag_mapping_options.[%parent.mapping_type]
      label: 'Mapping options'
    convert_targets:
      type: sequence
      label: 'Convert targets'
      sequence:
        type: thunder_print.tag_mapping_convert_targets
        # For >= 8.4
        orderby: key

# We default options to be empty and let each plugin define there own specific
# schema on their own.
thunder_print.tag_mapping_options.*:
  type: ignore

thunder_print.tag_mapping_options:
  type: mapping
  mapping:
    widget_type:
      type: string
      label: 'Widget type'
    field_settings:
      type: field.widget.settings.[%parent.widget_type]

thunder_print.tag_mapping_options.text_plain:
  type: thunder_print.tag_mapping_options
  mapping:
    title:
      type: boolean
      label: 'Can be used as title'

thunder_print.tag_mapping_convert_targets:
  type: mapping
  mapping:
    entity_type:
      type: string
      label: 'Can be used as title'
    property_path:
      type: string
      label: 'Can be used as title'
