thunder_print.tag_mapping.*:
  type: config_entity
  label: 'Tag Mapping config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    mapping_type:
      type: string
      label: 'Mapping type'
    mapping:
      type: sequence
      sequence:
        type: thunder_print.tag_mapping_map


thunder_print.tag_mapping_map:
  type: mapping
  mapping:
    property:
      type: string
      label: Property
    tag:
      type: string
      label: Tag
